### ISSUE TITLE
cloud credentials secret "noobaa-aws-cloud-creds-secret" is not ready yet

### ISSUE THREAD

**Issue by michaelschapira** [openshift/cloud-credential-operator#410]
OCP Version : 4.8.15
OCS Version: 4.8.3

Deployed OCP with CCO / STS. 

Installed OpenShift Container Storage Operator without any issue. Created a storage cluster via the UI. 

ocs-storagecluster-cephcluster deployed fine and is in ready state. 
noobaa is in `Configuring` state.  
Conditions show the following message:
```cloud credentials secret "noobaa-aws-cloud-creds-secret" is not ready yet```

there isn't any secret with that name. 
I cannot use IAM Account Key/Secret in my setup. 

I am expecting OCS to support CCO.

**Comment by joelddiaz** [comment]
When installing the cluster with STS, CCO is not processing CredentialsRequests from within the cluster. The user is responsible for taking a CredentialsRequest with the required list of permissions and creating the IAM Role and the eventual Secret holding the credentials. There is a `ccoctl` utility that can help take a CredentialsRequest and generate the IAM Role and Secret (which you can then apply to the cluster).

**Comment by michaelschapira** [comment]
Thanks for the quick response. 
I have used `ccoctl` the create the base role needed for the install of OCP

Is there documentation on what `CredentialsRequests` is needed for noobaa (ie from OCS), and how to generate it?

**Comment by joelddiaz** [comment]
A user is not expected to generate CredentialsRequest objects. The operator/component team would produce one as they know best which permissions are needed.
Each component typically includes a CredentialsRequest as part of the various k8s resources that are applied during installation. If you look at the output of `oc get -A credentialsrequests` you should see a list of all of the CredentialsRequests installed on the cluster. If noobaa does in fact rely on CredentialsRequests CRs, then one of those in the list (maybe more than one if noobaa has different permissions requirements for different clouds) will have been applied as part of the noobaa installation.
If noobaa does in fact create/apply a CredentialsRequest to the cluster, you'll see an object that looks something like https://github.com/openshift/cloud-credential-operator/blob/master/manifests/05-iam-ro-credentialsrequest.yaml

Whether noobaa is ready or not to accept using IAM Roles instead of static access_key/secret_key for authentication against AWS is something that team would know. But if the core operator hasn't been updated for this possibility, then they might have suggestions on next steps.
